# Generated by Django 2.0.7 on 2019-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=11)),
                ('dept', models.CharField(max_length=4)),
                ('semester', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
